# Diabetes 130-US Hospitals Dataset Analysis
Date: 25/12/2025 <br>
Group Name : Sampath Analytics

## Phase 1: Data Ingestion & Clinical Sanitation

This notebook performs data ingestion, cleaning, and preprocessing on the
"Diabetes 130-US Hospitals (1999–2008)" dataset.  
The objective of Phase 1 is to transform raw clinical data into a reliable
analytical dataset suitable for readmission analysis.

In [4]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

We import pandas for data manipulation, numpy for numerical operations, and visualization libraries for later phases.

In [5]:
# Load the diabetic data
df = pd.read_csv('diabetic_data.csv')

# Display first few rows
print("First 5 rows of the dataset:")
df.head()

First 5 rows of the dataset:

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,?,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,?,?,1,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,?,?,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,?,?,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,?,?,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,?,?,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO

We load the clinical dataset into a pandas DataFrame to begin our analysis.

In [6]:
# Check dataset dimensions
print(f"Dataset shape: {df.shape}")
print(f"Total rows: {df.shape[0]}, Total columns: {df.shape[1]}")

# View all column names
print("\nColumn names:")
print(df.columns.tolist())

# Get data types and non-null counts
print("\nData types and non-null information:")
df.info()

# Get summary statistics for numerical columns
print("\nSummary statistics:")
df.describe()

Dataset shape: (101766, 50)
Total rows: 101766, Total columns: 50

Column names:
['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight', 'admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'time_in_hospital', 'payer_code', 'medical_specialty', 'num_lab_procedures', 'num_procedures', 'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton', 'insulin', 'glyburide-metformin', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted']

Data types and non-null information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   weight                    101766 non-null  object
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  object
 11  medical_specialty         101766 non-null  object
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  object
 19  diag_2                    101766 non-null  object
 20  diag_3                    101766 non-null  object
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             5346 non-null    object
 23  A1Cresult                 17018 non-null   object
 24  metformin                 101766 non-null  object
 25  repaglinide               101766 non-null  object
 26  nateglinide               101766 non-null  object
 27  chlorpropamide            101766 non-null  object
 28  glimepiride               101766 non-null  object
 29  acetohexamide             101766 non-null  object
 30  glipizide                 101766 non-null  object
 31  glyburide                 101766 non-null  object
 32  tolbutamide               101766 non-null  object
 33  pioglitazone              101766 non-null  object
 34  rosiglitazone             101766 non-null  object
 35  acarbose                  101766 non-null  object
 36  miglitol                  101766 non-null  object
 37  troglitazone              101766 non-null  object
 38  tolazamide                101766 non-null  object
 39  examide                   101766 non-null  object
 40  citoglipton               101766 non-null  object
 41  insulin                   101766 non-null  object
 42  glyburide-metformin       101766 non-null  object
 43  glipizide-metformin       101766 non-null  object
 44  glimepiride-pioglitazone  101766 non-null  object
 45  metformin-rosiglitazone   101766 non-null  object
 46  metformin-pioglitazone    101766 non-null  object
 47  change                    101766 non-null  object
 48  diabetesMed               101766 non-null  object
 49  readmitted                101766 non-null  object
dtypes: int64(13), object(37)
memory usage: 38.8+ MB

Summary statistics:

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,1.017660e+05,1.017660e+05,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000
mean,1.652016e+08,5.433040e+07,2.024006,3.715642,5.754437,4.395987,43.095641,1.339730,16.021844,0.369357,0.197836,0.635566,7.422607
std,1.026403e+08,3.869636e+07,1.445403,5.280166,4.064081,2.985108,19.674362,1.705807,8.127566,1.267265,0.930472,1.262863,1.933600
min,1.252200e+04,1.350000e+02,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,8.496119e+07,2.341322e+07,1.000000,1.000000,1.000000,2.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,1.523890e+08,4.550514e+07,1.000000,1.000000,7.000000,4.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,2.302709e+08,8.754595e+07,3.000000,4.000000,7.000000,6.000000,57.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,4.438672e+08,1.895026e+08,8.000000,28.000000,25.000000,14.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000

We perform an initial audit to understand the structure, size, and data types of our dataset. This helps identify potential issues before cleaning

In [7]:
# Check for '?' in the dataset
print("Checking for '?' values in each column:")
for col in df.columns:
    question_mark_count = (df[col] == '?').sum()
    if question_mark_count > 0:
        print(f"{col}: {question_mark_count} occurrences")

# Replace '?' with NaN
df.replace('?', np.nan, inplace=True)

# Verify replacement
print("\nMissing values after replacement:")
print(df.isnull().sum()[df.isnull().sum() > 0])

Checking for '?' values in each column:
race: 2273 occurrences
weight: 98569 occurrences
payer_code: 40256 occurrences
medical_specialty: 49949 occurrences
diag_1: 21 occurrences
diag_2: 358 occurrences
diag_3: 1423 occurrences

Missing values after replacement:
race                  2273
weight               98569
payer_code           40256
medical_specialty    49949
diag_1                  21
diag_2                 358
diag_3                1423
max_glu_serum        96420
A1Cresult            84748
dtype: int64

The dataset uses '?' to represent missing values. We replace these with standard NaN values for proper handling in pandas.

In [8]:
# Calculate missing percentage for weight column
weight_missing_pct = (df['weight'].isnull().sum() / len(df)) * 100
print(f"Weight column missing percentage: {weight_missing_pct:.2f}%")

# Decision logic
if weight_missing_pct > 90:
    print(f"\nDropping 'weight' column due to {weight_missing_pct:.2f}% missingness")
    df.drop('weight', axis=1, inplace=True)
    print("Weight column dropped successfully")
else:
    print(f"\nWeight column retained (missing: {weight_missing_pct:.2f}%)")

# Verify
print(f"\nDataset shape after weight column handling: {df.shape}")

Weight column missing percentage: 96.86%

Dropping 'weight' column due to 96.86% missingness
Weight column dropped successfully

Dataset shape after weight column handling: (101766, 49)

The weight column has excessive missingness (>90%). Following data quality best practices, we drop columns with such high missing rates as they provide minimal analytical value. This is documented as a 'Data Quality Limitation' in our final report.

In [9]:
# Load the IDs mapping file
ids_mapping = pd.read_csv('IDs_mapping.csv')

print("IDs Mapping file structure:")
print(ids_mapping.head(20))

# The file contains three sections separated by empty rows
# We need to separate them for admission_type, discharge_disposition, and admission_source

# Create separate dataframes for each mapping type
# Find the empty rows to split the data
empty_rows = ids_mapping[ids_mapping.isnull().all(axis=1)].index.tolist()
print(f"\nEmpty row indices: {empty_rows}")

# Split into three sections
admission_type_df = ids_mapping.iloc[:empty_rows[0]].copy()
discharge_disp_df = ids_mapping.iloc[empty_rows[0]+1:empty_rows[1]].copy()
admission_source_df = ids_mapping.iloc[empty_rows[1]+1:].copy()

# Clean column names and create dictionaries
admission_type_df.columns = ['admission_type_id', 'admission_type_desc']
discharge_disp_df.columns = ['discharge_disposition_id', 'discharge_disposition_desc']
admission_source_df.columns = ['admission_source_id', 'admission_source_desc']

# Remove any remaining NaN rows
admission_type_df = admission_type_df.dropna()
discharge_disp_df = discharge_disp_df.dropna()
admission_source_df = admission_source_df.dropna()

print("\nAdmission Type Mappings:")
print(admission_type_df)
print("\nDischarge Disposition Mappings:")
print(discharge_disp_df.head(10))
print("\nAdmission Source Mappings:")
print(admission_source_df.head(10))

IDs Mapping file structure:
           admission_type_id  \
0                          1
1                          2
2                          3
3                          4
4                          5
5                          6
6                          7
7                          8
8                        NaN
9   discharge_disposition_id
10                         1
11                         2
12                         3
13                         4
14                         5
15                         6
16                         7
17                         8
18                         9
19                        10

                                          description
0                                           Emergency
1                                              Urgent
2                                            Elective
3                                             Newborn
4                                       Not Available
5                                                 NaN
6                                       Trauma Center
7                                          Not Mapped
8                                                 NaN
9                                         description
10                                 Discharged to home
11  Discharged/transferred to another short term h...
12  Discharged/transferred to a Skilled Nursing Fa...
13                      Discharged/transferred to ICF
14  Discharged/transferred to another type of inpa...
15  Discharged/transferred to home with home healt...
16                                           Left AMA
17  Discharged/transferred to home under care of H...
18          Admitted as an inpatient to this hospital
19  Neonate discharged to another hospital for neo...

Empty row indices: [8, 40]

Admission Type Mappings:
  admission_type_id admission_type_desc
0                 1           Emergency
1                 2              Urgent
2                 3            Elective
3                 4             Newborn
4                 5       Not Available
6                 7       Trauma Center
7                 8          Not Mapped

Discharge Disposition Mappings:
    discharge_disposition_id  \
9   discharge_disposition_id
10                         1
11                         2
12                         3
13                         4
14                         5
15                         6
16                         7
17                         8
18                         9

                           discharge_disposition_desc
9                                         description
10                                 Discharged to home
11  Discharged/transferred to another short term h...
12  Discharged/transferred to a Skilled Nursing Fa...
13                      Discharged/transferred to ICF
14  Discharged/transferred to another type of inpa...
15  Discharged/transferred to home with home healt...
16                                           Left AMA
17  Discharged/transferred to home under care of H...
18          Admitted as an inpatient to this hospital

Admission Source Mappings:
    admission_source_id                            admission_source_desc
41  admission_source_id                                      description
42                    1                               Physician Referral
43                    2                                  Clinic Referral
44                    3                                     HMO Referral
45                    4                         Transfer from a hospital
46                    5   Transfer from a Skilled Nursing Facility (SNF)
47                    6       Transfer from another health care facility
48                    7                                   Emergency Room
49                    8                            Court/Law Enforcement
50                    9                                    Not Available

We load the IDs_mapping.csv file which contains descriptions for coded values in our dataset. This will help us translate numerical IDs into meaningful categories.

In [10]:
# Identify "Expired" discharge disposition IDs
expired_ids = discharge_disp_df[
    discharge_disp_df['discharge_disposition_desc'].str.contains('Expired', case=False, na=False)
]['discharge_disposition_id'].values

print(f"Discharge disposition IDs for 'Expired' patients: {expired_ids}")

# Count deceased patients in dataset
deceased_count = df[df['discharge_disposition_id'].isin(expired_ids)].shape[0]
total_count = df.shape[0]
deceased_pct = (deceased_count / total_count) * 100

print(f"\nTotal patients in dataset: {total_count}")
print(f"Deceased patients: {deceased_count} ({deceased_pct:.2f}%)")

# Show some examples of deceased patients
print("\nSample of deceased patient records:")
print(df[df['discharge_disposition_id'].isin(expired_ids)].head())

Discharge disposition IDs for 'Expired' patients: ['11' '19' '20' '21']

Total patients in dataset: 101766
Deceased patients: 0 (0.00%)

Sample of deceased patient records:
Empty DataFrame
Columns: [encounter_id, patient_nbr, race, gender, age, admission_type_id, discharge_disposition_id, admission_source_id, time_in_hospital, payer_code, medical_specialty, num_lab_procedures, num_procedures, num_medications, number_outpatient, number_emergency, number_inpatient, diag_1, diag_2, diag_3, number_diagnoses, max_glu_serum, A1Cresult, metformin, repaglinide, nateglinide, chlorpropamide, glimepiride, acetohexamide, glipizide, glyburide, tolbutamide, pioglitazone, rosiglitazone, acarbose, miglitol, troglitazone, tolazamide, examide, citoglipton, insulin, glyburide-metformin, glipizide-metformin, glimepiride-pioglitazone, metformin-rosiglitazone, metformin-pioglitazone, change, diabetesMed, readmitted]
Index: []

Patients who expired (died) during their hospital stay cannot be readmitted. We identify these patients using discharge disposition codes 11, 19, 20, and 21 from the mapping file.

In [11]:
# Store original shape
original_shape = df.shape

# Filter out deceased patients
df_cleaned = df[~df['discharge_disposition_id'].isin(expired_ids)].copy()

# Verify removal
new_shape = df_cleaned.shape
rows_removed = original_shape[0] - new_shape[0]

print(f"Original dataset: {original_shape[0]} rows")
print(f"After removing deceased patients: {new_shape[0]} rows")
print(f"Rows removed: {rows_removed}")
print(f"Percentage removed: {(rows_removed/original_shape[0])*100:.2f}%")

# Update the main dataframe
df = df_cleaned.copy()

Original dataset: 101766 rows
After removing deceased patients: 101766 rows
Rows removed: 0
Percentage removed: 0.00%

We remove deceased patients from our analysis as they cannot be readmitted (our target variable). Including them would introduce noise into our readmission prediction model. This filtering improves the methodological rigor of our analysis.

In [12]:
# Check for exact duplicates
duplicate_count = df.duplicated().sum()
print(f"Number of exact duplicate rows: {duplicate_count}")

if duplicate_count > 0:
    print(f"\nRemoving {duplicate_count} duplicate rows...")
    df_before = df.shape[0]
    df = df.drop_duplicates()
    df_after = df.shape[0]
    print(f"Rows before: {df_before}")
    print(f"Rows after: {df_after}")
    print(f"Duplicates removed: {df_before - df_after}")
else:
    print("\nNo exact duplicates found. Dataset is clean.")

print(f"\nFinal dataset shape after Phase 1: {df.shape}")

Number of exact duplicate rows: 0

No exact duplicates found. Dataset is clean.

Final dataset shape after Phase 1: (101766, 49)

We check for and remove exact duplicate rows, which represent data entry errors. Note that multiple encounters per patient (same patient_nbr, different encounter_id) are valid and should NOT be removed.

In [13]:
# Identify ID columns that should be categorical
id_columns = ['admission_type_id', 'discharge_disposition_id', 'admission_source_id']

# Convert to categorical
for col in id_columns:
    if col in df.columns:
        df[col] = df[col].astype('category')
        print(f"Converted {col} to category type")

# Also convert other categorical text columns
categorical_text_cols = ['race', 'gender', 'age', 'payer_code', 'medical_specialty',
                         'max_glu_serum', 'A1Cresult', 'insulin', 'change', 
                         'diabetesMed', 'readmitted']

for col in categorical_text_cols:
    if col in df.columns:
        df[col] = df[col].astype('category')

print("\nData types after optimization:")
print(df.dtypes)

Converted admission_type_id to category type
Converted discharge_disposition_id to category type
Converted admission_source_id to category type

Data types after optimization:
encounter_id                   int64
patient_nbr                    int64
race                        category
gender                      category
age                         category
admission_type_id           category
discharge_disposition_id    category
admission_source_id         category
time_in_hospital               int64
payer_code                  category
medical_specialty           category
num_lab_procedures             int64
num_procedures                 int64
num_medications                int64
number_outpatient              int64
number_emergency               int64
number_inpatient               int64
diag_1                        object
diag_2                        object
diag_3                        object
number_diagnoses               int64
max_glu_serum               category
A1Cresult                   category
metformin                     object
repaglinide                   object
nateglinide                   object
chlorpropamide                object
glimepiride                   object
acetohexamide                 object
glipizide                     object
glyburide                     object
tolbutamide                   object
pioglitazone                  object
rosiglitazone                 object
acarbose                      object
miglitol                      object
troglitazone                  object
tolazamide                    object
examide                       object
citoglipton                   object
insulin                     category
glyburide-metformin           object
glipizide-metformin           object
glimepiride-pioglitazone      object
metformin-rosiglitazone       object
metformin-pioglitazone        object
change                      category
diabetesMed                 category
readmitted                  category
dtype: object

We optimize data types by converting ID and text columns to categorical type. This reduces memory usage and can improve performance for later operations.